<?php if(!defined('APPLICATION')) die();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Candy']['Modules']['BreadCrumbsAssetTarget'] = False;
$Configuration['Candy']['Modules']['BreadCrumbsLastCrumbLinked'] = False;
$Configuration['Candy']['Modules']['ShowAjarSideMenu'] = True;

